clear all;
global cincuenta;
cincuenta=imread('050.png');
global cien;
cien=imread('100.png');
global cientocincuenta;
cientocincuenta=imread('150.png');
global backback;
backback=imread('backback.png');
global bomb;
bomb=imread('bomb.png');
global django;
django=imread('django.png');
global explosion;
explosion=imread('explosion.png');
global glidder;
glidder=imread('glidder.png');
global jabi;
jabi=imread('jabi.png');
global montagon;
montagon=imread('montagon.png');
global paloma;
paloma=imread('pidgeon.png');
global fondo;
fondo=imread('pipes.png');
global sad;
sad=imread('sadglidder.png');
global swhat;
swhat=imread('saywhat.png');
save('imagenes.mat');
